### ISSUE TITLE
Wrong path to the endpoint

### ISSUE THREAD

**Issue by ygrigoriev** [romanzipp/Laravel-Twitch#111]
The path to `Get All Stream Tags` endpoint is wrong, - it should be `tags/streams` instead of `streams/tags`, please see the doc https://dev.twitch.tv/docs/api/reference#get-all-stream-tags

**Comment by romanzipp** [comment]
Fixed in [4.3.2](https://github.com/romanzipp/Laravel-Twitch/releases/tag/4.3.2), thanks!
