### ISSUE TITLE
Secret for EventSub (Question) 

### ISSUE THREAD

**Issue by chenchogalvan** [romanzipp/Laravel-Twitch#115]
maybe is a dumb question but... 

how can i create a secret for my EventSub? i need to get it from twitch  or just i need to write a simple word like a password?

**Comment by Katzen48** [comment]
You define the secret.
When you subscribe to a topic, the secret is sent to Twitch's EventSub system and all incoming notifications contain a signature, created with your secret.

This is for you, to verify the identity.
