### ISSUE TITLE
Result "status"

### ISSUE THREAD

**Issue by TheOfficialDroid** [romanzipp/Laravel-Twitch#122]
I'm going to keep this short, privatising "status" does nothing but add more work on someone using your package, for example getting a users subscribers, $var->status == 200/404, why make it more of a pain? Honestly......

**Comment by romanzipp** [comment]
I'm really sorry for providing a free Open Source package which you can freely use and [even modify](https://github.com/romanzipp/Laravel-Twitch/blob/master/LICENSE.md) (**wow!**).

You could have invested a little bit more time in scrolling through the [Result class](https://github.com/romanzipp/Laravel-Twitch/blob/master/src/Result.php#L108=) and would have discovered that there is a `getStatus` method which will serve your needs. Instead you have used your resources on drafting this disrespectful issue.

**Comment by TheOfficialDroid** [comment]
#59 

The irony

**Comment by romanzipp** [comment]
So what's you point?
