### ISSUE TITLE
Add Send Chat Announcement API Endpoint

### ISSUE THREAD

**Issue by kedesignzcom** [romanzipp/Laravel-Twitch#139]
In February 2023, IRC commands will be deprecated from non-twitch managed IRC.

We were instructed by Twitch Dev to use the new endpoint.
https://dev.twitch.tv/docs/api/reference/#send-chat-announcement

**Comment by ghostzero** [comment]
This is alreay implemented by this pull request: https://github.com/romanzipp/Laravel-Twitch/pull/134

The method you're referencing is `sendChatAnnouncement(array $parameters = [], array $body = [])`
