### ISSUE TITLE
TMI IRC Chatters list deprecation, New API Endpoint

### ISSUE THREAD

**Issue by kedesignzcom** [romanzipp/Laravel-Twitch#140]
The TMI endpoint for getting chatters will be deprecated, in favor of a new API endpoint.

Old endpoint was a URL and replacing "twitchdev" with the username of the user, which would return a list of chatters.
https://tmi.twitch.tv/group/user/twitchdev/chatters

New endpoint:
https://dev.twitch.tv/docs/api/reference/#get-chatters

**Comment by ghostzero** [comment]
This is alreay implemented by this pull request:

https://github.com/romanzipp/Laravel-Twitch/pull/138

The method you're referencing is `getChatters(array $parameters = [], ?Paginator $paginator = NULL)`
