### ISSUE TITLE
Subscribe Follow Endpoint

### ISSUE THREAD

**Issue by CodeWizardTV** [romanzipp/Laravel-Twitch#148]
Hi,

when i try to subscribe tot channel.follows endpoint i get the message "subscription missing proper authorization".
Where do i define scopes for the OAuth-Generator?

Kind regards,

Ron

**Comment by CodeWizardTV** [comment]
Sorry i've meant for the auto generated oauth.

Wouldn't it be good to also define which scopes should be used for it in the twitch-api.php

f.e.:

`
    'oauth_client_credentials' => [
        /*
         * Since May 01, 2020, Twitch requires all API requests to contain a valid Access Token.
         * This can be achieved with the Client Credentials flow.
         *
         * The package will attempt to generate a Access Token for unauthenticated requests.
         * NOTICE: This will only be enabled if a Client ID and Client Secret have been specified.
         */
        'auto_generate' => true,

        /*
         * Enable caching the Access Token to minimize workload.
         */
        'cache' => true,

        /*
        * Following scopes will be used for the generated oauth
        */
        'scopes' => [
            'user:read',
        ],


.
.
.

`

**Comment by romanzipp** [comment]
The auto generate feature only works for the [OAuth Client Credentials](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#client-credentials-grant-flow) flow which does not support scopes

**Comment by CodeWizardTV** [comment]
Oh ok i see. So i have to manage the User OAuth Flow by myself.

Thanks for your help and nice work!
