### ISSUE TITLE
Update GamesTrait to add igdb_id as query parameter

### ISSUE THREAD

**Issue by jenniferlieu** [romanzipp/Laravel-Twitch#153]
https://dev.twitch.tv/docs/api/reference/#get-games

The get games api now accepts igdb_id as a query parameter. So, the "igdb_id" needs to be added to the parameter array in the getGames function in GamesTrait.

Otherwise, when calling the getGames function with only the "igdb_id" field will throw a validation error.

**Comment by romanzipp** [comment]
Thanks! Fixed in 4.6.4
