### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by AboutSelphy** [romanzipp/Laravel-Twitch#155]
Hallo i have a question how to set this up :) 

im a little bit new to the backend part and for a future project i learn laraval and vue,

to understand it right;
1. composer laraval
2. composer twitchapi(this git)
3. setup env (the helix keys etc are from the console "application"?)

now it starts to beak for me.
the next step would be composer docs and test right? 
but well:
![image](https://github.com/romanzipp/Laravel-Twitch/assets/109421172/d404af0a-488f-4f9d-a503-92f8cb2c51f2)

It would be awesome helping me out with this ^^

**Comment by romanzipp** [comment]
You don't need to run the tests & docs command. This is only for developing **this package** - not your consuming application.

Just follow the [Installation](https://github.com/romanzipp/Laravel-Twitch?tab=readme-ov-file#installation) and [Configuration](https://github.com/romanzipp/Laravel-Twitch?tab=readme-ov-file#configuration) steps and you're ready to go.

**Comment by AboutSelphy** [comment]
alright thanks :) sorry if this sounds stupid, but i have to create controllers right ^^ ?
(beside configuration the router etc for every "call" i need i have to create a controller)

example: Controller::User (every action like Get etc)

i hope it will not annoy you :)

**Comment by romanzipp** [comment]
Yes, please take a look at some tutorials or the official documentation on how to use the Laravel framework. This is only a place to discuss issues with the Laravel-Twitch package.
