### ISSUE TITLE
Double encoding in $twitch->unsubscribeWebhook

### ISSUE THREAD

**Issue by IvanovPavel** [romanzipp/Laravel-Twitch#37]
Hi, use the last version of Laravel Twitch:
$twitch->unsubscribeWebhook(
        "https://***/twitch/callback/7",
        $twitch->webhookTopicStreamMonitor(190203376)
    );
After execute I've got a {"error":"Bad Request","status":400,"message":"hub.topic unsupported topic"}

Looked at params in request and saw:
hub.topic=https%253A%252F%252Fapi.twitch.tv%252Fhelix%252Fstreams%253Fuser_id%253D190203376

`%253A%252F%252F`
It's not the same as `%3A%2F%2F` as it get after urlencode()
Could you fix it?

BTW: use
"name": "guzzlehttp/guzzle",
"version": "6.3.3",

**Comment by romanzipp** [comment]
Could you try out the latest `dev-master` version? I'll file a release if can confirm your issues is solved by that.

**Comment by IvanovPavel** [comment]
Hmm, there is only one branch Master. Could you help me to get the right way for composer to get version for test?
