### ISSUE TITLE
Support Laravel 7

### ISSUE THREAD

**Issue by BulgarianHealer** [romanzipp/Laravel-Twitch#41]
Can you add support for laravel 7? Thanks.

**Comment by romanzipp** [comment]
Laravel 7 [is not released yet](https://github.com/laravel/framework/releases). I'll add support when there's a new release since everything is subject to change.

**Comment by romanzipp** [comment]
You can fork the repository and add your own dependency support by then integrating the package [as a composer repository](https://github.com/laravel/framework/releases)

**Comment by BulgarianHealer** [comment]
I know, but only your package is stopping me from testing L7. Yes, I was thinking of that(forking), but I think that you can create a dev version?

**Comment by BulgarianHealer** [comment]
@romanzipp Check out RP #42

**Comment by romanzipp** [comment]
Merged #43
