### ISSUE TITLE
OAuth authorization `force_verify` not working

### ISSUE THREAD

**Issue by alexbcberio** [romanzipp/Laravel-Twitch#44]
In OAuth Authorizations there's a field to specify if you want to force user verification, as Twitch docs says:

> Specifies whether the user should be re-prompted for authorization. If this is `true`, the user always is prompted to confirm authorization. This is useful to allow your users to switch Twitch accounts, since there is no way to log users out of the API. Default: `false` (a given user sees the authorization page for a given set of scopes only the first time through the sequence).

This is not working propertly as PHP is converting the "true" and "false" values to the integers 1 and 0 and what Twitch expects are values as the strings `true` or `false`.

**Comment by romanzipp** [comment]
Oh, I would have never though this would be problem. Fixed in [2.2.2](https://github.com/romanzipp/Laravel-Twitch/releases/tag/2.2.2)

**Comment by alexbcberio** [comment]
Thanks for the fast fix!

Updated to 2.2.2 and working as expected.
