### ISSUE TITLE
getUserSubscriptions() not working

### ISSUE THREAD

**Issue by patrickghg** [romanzipp/Laravel-Twitch#45]
public function getSubscriptions(array $parameters = array (), Paginator $paginator = NULL)

I think there is twist, the function getSubscriptions() is not working, I get an error message: Missing required parameter "broadcaster_id.

Twitch seems to removed this endpoint in https://dev.twitch.tv/docs/api/reference/#get-broadcaster-subscriptions. There is no method to check the users subscription list at the moment.

**Comment by patrickghg** [comment]
You have to use v3/v5 to get the subscriptions a user has.

**Comment by romanzipp** [comment]
Oh, I wasn't aware that Twitch has removed the option to get user subscriptions without a broadcaster. Will mark the `getUserSubscriptions` method as deprecated 👍
