### ISSUE TITLE
A getAppToken() method is missing

### ISSUE THREAD

**Issue by iWhited** [romanzipp/Laravel-Twitch#46]
Hi there,
I can't find a way to get an App Token with the package. I think this method in **romanzipp\Twitch\Trait\OAuthTrait** could be useful to do that : 
```
public function getAppToken(array $scopes = []): Result
    {
        $parameters = [
            'client_id'     => $this->getClientId(),
            'client_secret' => $this->getClientSecret($scopes),
            'grant_type'    => "client_credentials",
            'scope'         => $this->buildScopes($scopes)
        ];

        return $this->post(self::OAUTH_BASE_URI . 'token', $parameters);
    }
```
I'm referring with [https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-client-credentials-flow](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-client-credentials-flow)

**Comment by romanzipp** [comment]
I've added more optional parameters to the `getOAuthToken` method as seen in #48 
Will this work for you?

**Comment by romanzipp** [comment]
[2.2.4](https://github.com/romanzipp/Laravel-Twitch/releases/tag/2.2.4) has been released
