### ISSUE TITLE
Upcoming changes to authorization starting May 1, 2020

### ISSUE THREAD

**Issue by Katzen48** [romanzipp/Laravel-Twitch#47]
Starting May 1, 2020 Bearer Tokens become mandatory.
Requests using only Client IDs will be dropped.
https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

I would appreciate a support for automatic requests of app access token, when no token is provided.

**Comment by romanzipp** [comment]
I'll take a look at this. Do you know any other packages that already follow a similar behavior?

**Comment by romanzipp** [comment]
I've filed draft, see #52

**Comment by Katzen48** [comment]
Looks good, I'll test the new feature.
Thanks.
