### ISSUE TITLE
Exception when Response is null

### ISSUE THREAD

**Issue by Katzen48** [romanzipp/Laravel-Twitch#50]
I iterate over the getStreams() and at some point, I get the following exception.

![image](https://user-images.githubusercontent.com/19516002/80641907-e1a15c80-8a65-11ea-94a8-55cf9a03cdee.png)

**Comment by ghostzero** [comment]
![image](https://user-images.githubusercontent.com/6547306/80646245-ab1b1000-8a6c-11ea-8349-df6c68877dcd.png)

Small throw-in, when we are already at this point^^

**Comment by romanzipp** [comment]
Got it. Pretty weird that there is no response in a RequestException, could have been a transfer issue.
Could you take a look at #51 ?

**Comment by ghostzero** [comment]
Thank you! I have reviewed the changes. Looks great!

**Comment by romanzipp** [comment]
I've released [2.2.3](https://github.com/romanzipp/Laravel-Twitch/releases/tag/2.2.3)
