### ISSUE TITLE
Undefined property: stdClass::$cursor

### ISSUE THREAD

**Issue by IvanovPavel** [romanzipp/Laravel-Twitch#53]
Sometimes I've got an error in this row of code
`$result = $twitch->getStreams($params, isset($result) ? $result->next() : null);`

> Undefined property: stdClass::$cursor

**Comment by romanzipp** [comment]
It looks like you are trying to fetch a new set of results although there is no next-cursor in the previous result.

I've created a PR #54 adding a new `Result::hasMoreResults()`. Could check if this works for you?

Replace your current composer version of this package with `"romanzipp/laravel-twitch": "dev-fix-paginator"` for testing purposes.

**Comment by romanzipp** [comment]
I've also updated the [README pagination example](https://github.com/romanzipp/Laravel-Twitch/tree/fix-paginator#pagination-loop-example) according to the new API

**Comment by ghostzero** [comment]
Can also confirm the bug. I have your fix branch now in the production branch on my website. Runs fine on my side!
