### ISSUE TITLE
New Twitch Api get authenticated user

### ISSUE THREAD

**Issue by dehghanimehrdad** [romanzipp/Laravel-Twitch#56]
Hello,
I couldn't get the current user using only the oauth token, according to documentations if the getUsers endpoint is called with no parameters it will return the current user, but since the parameters on you implementation was required I couldn't get it working.

removing the line:

`
if ( ! array_key_exists('login', $parameters) && ! array_key_exists('id', $parameters)) {
            throw new InvalidArgumentException('Parameter required missing: name or id');
        }
`
from UsersTrait.php getUsers method solved this for me with an empty array as parameter.

**Comment by romanzipp** [comment]
I'm pretty sure they have changed the query parameter requirement for the users endpoint.

Could you try out the `getAuthedUser()` method (not documented because I marked it as deprecated)?

**Comment by dehghanimehrdad** [comment]
> I'm pretty sure they have changed the query parameter requirement for the users endpoint.
> 
> Could you try out the `getAuthedUser()` method (not documented because I marked it as deprecated)?

I did check `getAuthedUser()` and it was working but since it was marked as deprecated I thought it wouldn't be a good idea to use it, so I tried sending the getUsers request with no parameter and it worked fine. I think you should check and maybe implement it so there won't be a need for hard coding the library.

**Comment by romanzipp** [comment]
I've tagged [2.3.2](https://github.com/romanzipp/Laravel-Twitch/releases/tag/2.3.2) which makes parameters for the `getUsers` method optional and removes the argument check
