### ISSUE TITLE
How to realize a login?

### ISSUE THREAD

**Issue by NormanHuth** [romanzipp/Laravel-Twitch#59]
I plan to login via Twitch.

I have a login view.
```php
    public function login()
    {
        return view('auth.login', [
            'authorize_url' => $this->twitch->getOAuthAuthorizeUrl($responseType = 'code')
        ]);
    }
```

I can get the code.
```php
    public function callback(Request $request)
    {
        Log::info($request->code);
    }
```

But how do I get the information like email address, Twitch username & Twitch-ID from this user?

**Comment by romanzipp** [comment]
You can obtain the OAuth Access & Refresh Token using the [Twitch::getOAuthToken($code)](https://github.com/romanzipp/Laravel-Twitch/blob/2.3.2/src/Concerns/Api/OAuthTrait.php#L51) method. This is also documented on the [Twitch Dev Docs](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth) page.

Although, I would recommend using [Laravel Sociliate](https://laravel.com/docs/7.x/socialite) with the new [Socialite Twitch Provider](https://socialiteproviders.netlify.app/providers/twitch.html) for handling OAuth.

**Comment by NormanHuth** [comment]
With this package and socialite the message: "invalid client secret" appears again and again. And this one is just like on Twitch. I've checked all the data a thousand times.

I don't know what's wrong with Twicht or what I should do about it.

**Comment by ghostzero** [comment]
This package (Laravel-Twitch) comes with the follwing env variables:

```env
TWITCH_HELIX_KEY=
TWITCH_HELIX_SECRET=
TWITCH_HELIX_REDIRECT_URI=http://localhost
```

You have to change the following from the [4. Configuration setup tutorial](https://socialiteproviders.netlify.app/providers/twitch.html#_4-configuration-setup) to make the Twitch Socialite Provider compatible with Laravel-Twitch:

From:

```env
'twitch' => [
    'client_id' => env('TWITCH_KEY'),
    'client_secret' => env('TWITCH_SECRET'),
    'redirect' => env('TWITCH_REDIRECT_URI')
],
```

To:

```
'twitch' => [
    'client_id' => env('TWITCH_HELIX_KEY'),
    'client_secret' => env('TWITCH_HELIX_SECRET'),
    'redirect' => env('TWITCH_REDIRECT_URI')
],
```

Thus the Twitch Socialite Provider uses the same credentials as for Laravel-Twitch.

**Comment by NormanHuth** [comment]
I had that first. Twitch keeps telling me that my client secret is wrong. Even with Postman. Other APIs (Facebook, Google, Steam etc) run without problems, just not theirs. I think their API just sucks.
