### ISSUE TITLE
Suggestion: Add EventSub Endpoints

### ISSUE THREAD

**Issue by Katzen48** [romanzipp/Laravel-Twitch#67]
Twitch released a new product called "EventSub", which allows subscribing to event notifications via multiple different transport types (including WebHooks):
https://dev.twitch.tv/docs/eventsub

This introduces new Endpoints to the Helix namespace.

**Comment by ghostzero** [comment]
Related to the #69 pull request.

**Comment by Katzen48** [comment]
Could the headers "Twitch-Eventsub-Message-Id", "Twitch-Eventsub-Message-Retry" and "Twitch-Eventsub-Message-Timestamp" be added to the EventSub events as attributes?

Currently, when there is a problem and events are resent by EventSub, there is no indication, when the event was fired initially, how many retries were necessary or if the same message was sent multiple times.

**Comment by ghostzero** [comment]
Feel free to create a pull request @Katzen48 :D

Currently I'm using `app(Request::class)->header('twitch-eventsub-message-id')`, for example to get the message id.
