### ISSUE TITLE
Question: Cache Driver

### ISSUE THREAD

**Issue by ghostzero** [romanzipp/Laravel-Twitch#70]
Why do we have to define a cache driver? It is already defined in the store configuration.

```php
/*
 * The cache driver to use for storing Client Credentials.
 */
'cache_driver' => null,
```

**Comment by Katzen48** [comment]
It's for example for the automated generation of an app access token: https://github.com/romanzipp/Laravel-Twitch/blob/3cddb14dd4077f094a82912086e9cc8601b14b9a/src/Concerns/AuthenticationTrait.php#L113

**Comment by ghostzero** [comment]
Please look how it is implemented, not only the usage. I also created a pull request for this #72.

I mean you define the driver within the store in `cache.php`:

```
'stores' => [
    'redis' => [
        'driver' => 'redis',
        'connection' => 'cache',
    ],
],
```

The method `driver($driver = null)` calls literally the method `store()` within the CacheManager of Laravel. So the `getClientCredentialsCacheRepository` method will call `store(...)` twice, but with different configurations.

So if you define as `cache_driver=file`, and then `cache_store=redis`, you only use redis and your real driver is redis.
