### ISSUE TITLE
Bug: Auto Generate does not work properly.

### ISSUE THREAD

**Issue by ghostzero** [romanzipp/Laravel-Twitch#71]
I have the feeling that the oauth client credentials cache does not renew expired keys.

I have the problem almost every month that I get the response `Invalid OAuth token` from the Twitch API.

Unfortunately I could not look at it. Workaround was: Change cache key.

**Comment by ghostzero** [comment]
After some research I came across the following:

> The API limits the number of active access tokens associated with a given refresh token. The limit is 50 token per client/user (that is, a user can only have 50 tokens live at a time per client ID).

Maybe my app generated too many tokens and after some time Twitch invalidated the cached token. So the token is probably invalid in the cache and will not be deleted for further requests. All subsequent requests will be rejected with an 'Invalid OAuth token'.

Source: https://dev.twitch.tv/docs/authentication#:~:text=The%20API%20limits%20the%20number,a%20time%20per%20client%20ID).

**Comment by romanzipp** [comment]
I also encountered this issue. In response, I've added [some changes](https://github.com/romanzipp/Laravel-Twitch/pull/74/commits/e2c3cd7b8dbac765bfdb935184dd7a0923839785) to clear the cached API client credentials if the API response indicates that the given OAuth token is invalid

**Comment by romanzipp** [comment]
Fied in [v4.0.0](https://github.com/romanzipp/Laravel-Twitch/releases/tag/4.0.0)
