### ISSUE TITLE
Lack of release for latest patch

### ISSUE THREAD

**Issue by tystuyfzand** [romanzipp/Laravel-Twitch#8]
https://github.com/romanzipp/Laravel-Twitch/commit/c734c5bd0521da5553e68682776ef646a51c76d5 is missing a release, causing the error to occur under certain circumstances - specifically, ide-helper:generate from https://github.com/barryvdh/laravel-ide-helper

`PHP Fatal error:  Declaration of romanzipp\Twitch\Traits\UsersTrait::withToken() must be compatible with romanzipp\Twitch\Traits\ExtentionsTrait::withToken(string $token)`

**Comment by romanzipp** [comment]
I've just released v1.0.12 - Thanks!
