### ISSUE TITLE
Tolerance

### ISSUE THREAD

**Issue by VoronVoronov** [romanzipp/Laravel-Twitch#92]
The time zone in laravel is specified in Moscow, in" tolerance " it is specified in 180,but the question is what should be specified in minutes or in seconds?

**Comment by romanzipp** [comment]
Same as #95 

Could you try out #98 ? This PR introduces time comparisons via Carbon

```
"romanzipp/laravel-twitch": "dev-fix-event-sub-verification-tolerance",
```

**Comment by VoronVoronov** [comment]
> Same as #95
> 
> Could you try out #98 ? This PR introduces time comparisons via Carbon
> 
> ```
> "romanzipp/laravel-twitch": "dev-fix-event-sub-verification-tolerance",
> ```

it`s good, thanks
