### ISSUE TITLE
Button "Connection with twich"

### ISSUE THREAD

**Issue by jcanto05000** [romanzipp/Laravel-Twitch#94]
Hello, I am a beginner of Laravel.
I would like to create a "Connect with Twich" button. The goal is to retrieve the twitch id and twitch username of the user who wants to connect.

I followed your documentation but I cannot create my controller using your code.

I have correctly set the "clientid", "clientsecret", "redirect" information.

Can you explain the procedure to me in detail?

I work with Laravel 8.
Thank you so much.

**Comment by romanzipp** [comment]
If you're using Laravel to authenticate users through Twitch, you should use [**Laravel Socialite**](https://laravel.com/docs/8.x/socialite) with the [Socialite Twitch Provider](https://socialiteproviders.com/Twitch/#twitch).

I would not recommend to implement it yourself using this library if you're a beginner.

**Comment by jcanto05000** [comment]
Hello.

Thank you very much for your advice !
