### ISSUE TITLE
Problem with laravel timezone

### ISSUE THREAD

**Issue by alitnk** [romanzipp/Laravel-Twitch#95]
First of all, thanks for the amazing package.

When I set app.php's zime zone to my local time zone, the eventsub webhook URL keeps throwing `SignatureVerificationException` with the message `Timestamp outside the tolerance zone`, it works when I set it back to Laravel's default though.

Is this perhaps a problem on my side?

**Comment by romanzipp** [comment]
That's strange. PHP should always use the UTC timestamps in both `time` and `strototime` functions when comparing the header and current timestamps.

Could you try out #97 ? This PR introduces time comparisons via Carbon

**Comment by alitnk** [comment]
Thanks for the response,

I tried the PR, I confirm it works with my time zone.

**Comment by ghostzero** [comment]
> That's strange. PHP should always use the UTC timestamps in both `time` and `strototime` functions when comparing the header and current timestamps.

`strototime` and `time` takes the time set in PHP. This can actually cause problems if you have not set your system time to UTC. I can reproduce it by the following example:

```php
<?php

// Europe/Berlin
echo date_default_timezone_get() . PHP_EOL;

// 1619729603
echo strtotime('2021-04-29 22:53:23') . PHP_EOL;

date_default_timezone_set('America/New_York');

// 1619751203
echo strtotime('2021-04-29 22:53:23') . PHP_EOL;

// 1619729603 !== 1619729603
```
